version: '3'
services:
    rabbit:
        hostname: rabbit
        image: rabbitmq:3-management
        networks:
            testing_net:
                ipv4_address: 172.28.0.2  #cpp couldn't resolve host rabbit, had to put ip      

    consumer:
        build:
            context: ./consume
            dockerfile: Dockerfile
        links:
            - rabbit
        depends_on:
            - rabbit
        networks:
            - testing_net
        environment:
            - RABBITMQ_HOST_IP=docker.for.mac.host.internal
            - RABBITMQ_USER=admin
            - RABBITMQ_PASSWORD=admin
            - RABBITMQ_PORT=5672
            - RABBITMQ_VIRTUAL_HOST=/
            - RABBITMQ_QUEUE_FROM=test
            - LD_LIBRARY_PATH=/usr/local/lib
        volumes:
            - .:/app
        working_dir: /app

    publish:
        build:
            context: ./publish
            dockerfile: Dockerfile
        links:
            - rabbit
        depends_on:
            - rabbit
        networks:
            - testing_net
        environment:
            - RABBITMQ_HOST_IP=docker.for.mac.host.internal
            - RABBITMQ_USER=admin
            - RABBITMQ_PASSWORD=admin
            - RABBITMQ_PORT=5672
            - RABBITMQ_VIRTUAL_HOST=/
            - RABBITMQ_QUEUE_FROM=test
            - LD_LIBRARY_PATH=/usr/local/lib
        volumes:
            - .:/app
        working_dir: /app

networks:
    testing_net:
        ipam:
            driver: default
            config:
                - subnet: 172.28.0.0/16
